// Builds every launcher, splash and notification icon from android/branding/app-icon.png.
// The artwork itself is never changed, only scaled. Run from the repo root:  node android/branding/make-icons.mjs
//
// Adaptive icon (Android 8+): 108dp layers, of which launchers show at most the middle 72dp
// (and only a 66dp circle is guaranteed). The artwork is placed at 80dp, so its own square
// edges always sit outside what any launcher shows, while the "V" (within 77% of the artwork)
// stays inside the 66dp safe circle. Nothing of the logo is ever cut off.
import sharp from "sharp";
import fs from "node:fs";

const SRC = "android/branding/app-icon.png";
const RES = "android/app/src/main/res";
const DENSITIES = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };
const ART_DP = 80;
const LAYER_DP = 108;

const write = async (dir, name, buf) => {
  fs.mkdirSync(`${RES}/${dir}`, { recursive: true });
  fs.writeFileSync(`${RES}/${dir}/${name}`, buf);
};

for (const [d, k] of Object.entries(DENSITIES)) {
  const layer = Math.round(LAYER_DP * k);
  const art = Math.round(ART_DP * k);
  const scaled = await sharp(SRC).resize(art, art, { kernel: "lanczos3" }).png().toBuffer();
  // Adaptive foreground: artwork centred on a transparent 108dp layer.
  const fg = await sharp({ create: { width: layer, height: layer, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite([{ input: scaled, left: Math.round((layer - art) / 2), top: Math.round((layer - art) / 2) }])
    .png({ compressionLevel: 9 })
    .toBuffer();
  await write(`mipmap-${d}`, "ic_launcher_foreground.png", fg);

  // Older launchers (Android 7): the artwork as it is, square and round.
  const legacy = Math.round(48 * k);
  await write(`mipmap-${d}`, "ic_launcher.png", await sharp(SRC).resize(legacy, legacy).png({ compressionLevel: 9 }).toBuffer());
  const circle = Buffer.from(`<svg width="${legacy}" height="${legacy}"><circle cx="${legacy / 2}" cy="${legacy / 2}" r="${legacy / 2}" fill="#fff"/></svg>`);
  await write(`mipmap-${d}`, "ic_launcher_round.png", await sharp(SRC).resize(legacy, legacy).composite([{ input: circle, blend: "dest-in" }]).png({ compressionLevel: 9 }).toBuffer());

  // Status-bar notification icon: Android wants a white shape on transparent; taken from the logo's bright parts.
  const n = Math.round(24 * k);
  const { data, info } = await sharp(SRC).resize(n, n).raw().toBuffer({ resolveWithObject: true });
  const out = Buffer.alloc(n * n * 4);
  for (let i = 0; i < n * n; i++) {
    const lum = (data[i * info.channels] + data[i * info.channels + 1] + data[i * info.channels + 2]) / 3;
    out[i * 4] = out[i * 4 + 1] = out[i * 4 + 2] = 255;
    out[i * 4 + 3] = Math.max(0, Math.min(255, Math.round((lum - 45) * 4)));
  }
  await write(`drawable-${d}`, "ic_stat_notify.png", await sharp(out, { raw: { width: n, height: n, channels: 4 } }).png({ compressionLevel: 9 }).toBuffer());
}

// Colours that continue the artwork's own background beyond its edges.
const { data, info } = await sharp(SRC).raw().toBuffer({ resolveWithObject: true });
const at = (x, y) => { const i = (y * info.width + x) * info.channels; return [data[i], data[i + 1], data[i + 2]]; };
const avg = (pts) => pts.reduce((a, p) => a.map((v, j) => v + p[j] / pts.length), [0, 0, 0]).map(Math.round);
const hex = (c) => "#" + c.map((v) => v.toString(16).padStart(2, "0")).join("");
const edge = avg([...Array(64)].flatMap((_, i) => { const t = Math.round((i / 63) * 1023); return [at(t, 0), at(t, 1023), at(0, t), at(1023, t)]; }));
// The splash shows the artwork in a circle; its background matches the artwork where that circle ends.
const r = Math.round(1024 * (96 / ((ART_DP / LAYER_DP) * 288)));
const ring = avg([...Array(180)].map((_, i) => { const a = (i / 180) * 2 * Math.PI; return at(Math.round(512 + r * Math.cos(a)), Math.round(512 + r * Math.sin(a))); }));
fs.mkdirSync(`${RES}/values`, { recursive: true });
fs.writeFileSync(
  `${RES}/values/icon_colors.xml`,
  `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by android/branding/make-icons.mjs from the app icon's own colours. -->\n<resources>\n    <color name="ic_launcher_background">${hex(edge)}</color>\n    <color name="splash_background">${hex(ring)}</color>\n</resources>\n`,
);
console.log("edge", hex(edge), "splash ring", hex(ring), "r", r);
